function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(5)=params(11)*exp(params(1))^(params(12)*(1-params(2))-1);
    YKbar=(1/ys_(5)-(1-params(4)))/(1-params(8));
    ys_(12)=1+(1-exp(params(1))-params(4))*1/YKbar-(1-exp(params(1))*ys_(5))*params(13);
    ys_(7)=params(12)*params(8)/(params(12)*params(8)+ys_(12)-params(12)*ys_(12));
    ys_(2)=(exp(params(1))^params(8)*ys_(7)^params(8)/YKbar)^(1/params(8));
    ys_(3)=ys_(2)^(1-params(8))*(exp(params(1))*ys_(7))^params(8);
    ys_(1)=ys_(12)*ys_(3);
    ys_(14)=ys_(2)*(params(4)+exp(params(1))-1);
    params(7)=params(13)*ys_(3);
    ys_(15)=(ys_(3)-ys_(1)-ys_(14))/ys_(3);
    params(10)=1/ys_(5)-1;
    ys_(4)=params(7);
    ys_(9)=0;
    ys_(6)=params(1);
    ys_(8)=(ys_(1)^params(12)*(1-ys_(7))^(1-params(12)))^(1-params(2))/(1-params(2));
    ys_(10)=(1-params(2))*params(12)*ys_(8)/ys_(1);
    ys_(11)=(1-params(2))*ys_(8)*(-(1-params(12)))/(1-ys_(7));
    ys_(13)=(ys_(2)*exp(ys_(6))-(1-params(4))*ys_(2))/ys_(3);
    ys_(16)=log(ys_(13));
    ys_(17)=log(ys_(12));
    ys_(18)=log(ys_(3));
    ys_(19)=log(ys_(1));
    ys_(20)=log(ys_(14));
    ys_(21)=params(1);
    % Auxiliary equations
end
